### ISSUE TITLE
`skygear.config` fails when the module is not specify in `skygear.options.modules`

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/py-skygear#103]
After merging #102, modules specified in `skygear.options.modules` will be loaded. However, when using `skygear.config` in `__init__.py`, it cannot find the module.

This can be reproduce by the following `__init__.py`:
```
import skygear

skygear.config("some_module")
```

And running:
```
$ py-skygear --subprocess event init

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/skygear/settings/module.py", line 34, in get_module
    return loaded_modules[name]
KeyError: 'some_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/skygear/settings/__init__.py", line 94, in config_module
    module = get_module(name)
  File "/usr/local/lib/python3.5/site-packages/skygear/settings/module.py", line 36, in get_module
    raise NameError("name '{}' is not defined".format(name))
NameError: name 'some_module' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/py-skygear", line 9, in <module>
    load_entry_point('skygear==0.19.0', 'console_scripts', 'py-skygear')()
  File "/usr/local/lib/python3.5/site-packages/skygear/bin.py", line 37, in main
    run_plugin(options)
  File "/usr/local/lib/python3.5/site-packages/skygear/bin.py", line 75, in run_plugin
    load(options)
  File "/usr/local/lib/python3.5/site-packages/skygear/bin.py", line 64, in load
    load_modules(options.modules)
  File "/usr/local/lib/python3.5/site-packages/skygear/importutil.py", line 118, in load_modules
    load_module(module)
  File "/usr/local/lib/python3.5/site-packages/skygear/importutil.py", line 78, in load_module
    loaded = SourceFileLoader(package_name, loadpath).load_module()
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./__init__.py", line 5, in <module>
    skygear.config('some_module')
  File "/usr/local/lib/python3.5/site-packages/skygear/settings/__init__.py", line 96, in config_module
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'some_module'
```

**Comment by ben181231** [comment]
I cannot reproduce it using current master branch.
