### ISSUE TITLE
Run py-skygear appear Traceback Error

### ISSUE THREAD

**Issue by mmok1234** [SkygearIO/py-skygear#111]
When I run py-skygear on my mac:

`Traceback (most recent call last):
  File "/usr/local/bin/py-skygear", line 6, in <module>
    from pkg_resources import load_entry_point

  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside

  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)

  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()

  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)

  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))

  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
    
pkg_resources.DistributionNotFound: The 'skygear' distribution was not found and is required by the application`

**Comment by rickmak** [comment]
May I know how you install py-skygear.

Looks like permission problem.
