### ISSUE TITLE
py-skyegar cannot start without zmq module

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/py-skygear#13]
On a fresh install environment, cannot start `py-skygear` unless manually install `pyzmq`

- Skygear Server Date/Version: v0.10
- Application Platform: python3.5
- [x] Is this a regression?
- [x] Attached logs, screenshots

#### Expected Results
`py-skygear started`

#### Actual Results
``` python
Traceback (most recent call last):
  File "/Users/rickmak/Working/chima-fb/pyenv/bin/py-skygear", line 7, in <module>
    from skygear.bin import main
  File "/Users/rickmak/Working/chima-fb/pyenv/lib/python3.5/site-packages/skygear/bin.py", line 21, in <module>
    from .transmitter import ConsoleTransport, HttpTransport, ZmqTransport
  File "/Users/rickmak/Working/chima-fb/pyenv/lib/python3.5/site-packages/skygear/transmitter/__init__.py", line 15, in <module>
    from .zmq import ZmqTransport
  File "/Users/rickmak/Working/chima-fb/pyenv/lib/python3.5/site-packages/skygear/transmitter/zmq.py", line 19, in <module>
    import zmq
ImportError: No module named 'zmq'
```

#### Steps to reproduce

1. virtualenv --python=python3 pyenv
2. pip install skygear
3. py-skygear \__init\__.py

**Comment by ben181231** [comment]
@rickmak So I need to update `setup.py` and add `pyzmq` as dependency ?
