### ISSUE TITLE
SkygearContainer missing when construct 

### ISSUE THREAD

**Issue by samMeow** [SkygearIO/py-skygear#160]
SkygearContainer.transport is NoneType and return error when invoking `send_action`
when using demo code like 
```python
from skygear.container import SkygearContainer

container = SkygearContainer(api_key="your-api-key")
def last_promo_code():
    query = {
        'database_id': '_public',
        'record_type': 'promo_code',
        'limit': 1,
        'sort': [
            [{
                '$type': 'keypath',
                '$val': '_updated_at'
            }, 'desc' ]
        ]
    }
    response = container.send_action('record:query', query)
    records = response.get('result', []) # returned rows are in 'result'
    # `records` is an array of dict
    task = records[0]
    return task
```
Error raised as below,
```
Traceback (most recent call last):
  File "server/promocode.py", line 30, in <module>
    print(last_promo_code())
  File "server/promocode.py", line 23, in last_promo_code
    response = container.send_action('record:query', query)
  File "/usr/local/lib/python3.6/site-packages/skygear/container.py", line 106, in send_action
    resp = self.transport.send_action(action_name, payload, url, timeout)
AttributeError: 'NoneType' object has no attribute 'send_action'
```
Questions: 
Do user need to import lib themselves `from skygear.transmitter.http import HttpTransport`?  If yes, what is the addr needed to put for param `http://localhost:3000`
Is a default Transport should be construct when a SkygearContainer is constructed?

**Comment by samMeow** [comment]
connect #158
